[workspace.package]
edition = "2024"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
version = "0.1.0"

[workspace]
resolver = "3"
members = [
    "shrink_wrap",
    "shrink_wrap_core",
    "shrink_wrap_derive",
]
